version: "3.9"
services:
  lgsfrontend:
    env_file:
    - .env
    image: quay.io/labyrinthglobalsolutions/lgs-frontend:${IMAGE_TAG}
    restart: always
    labels:
      - traefik.frontend.rule=Host:labyrinthglobalsolutions.com,www.labyrinthglobalsolutions.com
    networks:
     - web
    ports:
      - "3008:3008"
networks:
 web:
   external: true